engines:
  duplication:
    enabled: false
  checks:
    Similar code:
      enabled: false
  config:
    languages:
    - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- "node_modules/**/*"
